openapi: 3.0.0
info:
  version: 0.0.1
  title: yagna-poc-classifier
  contact:
    name: Golem Apps & Cooperations Team
    email: apps-team@golem.network
  description: 
      Proof-of-concept of long running tasks on Golem network which leverages chosen 
      text classifiers.
servers:
  - url: 'http://localhost:3000/api'

paths:
  /classify:
    post:
      summary: Classifies posted text
      operationId: post-classify
      tags:
        - classification
      responses:
        '200':
          description: Responses retrieved from classifiers
          content:
            application/json:
                schema:
                    $ref: '#/components/schemas/TextClassificationResult'
                example:
                    emotion:
                      -
                          label: 'love'
                          score: 0.005923508666455746
                      -
                          label: 'joy'
                          score: 0.38369229435920715
                      -
                          label: 'surprise'
                          score: 0.6015767455101013
                    summary:
                      summary_text: >
                          The tower is 324 metres (1,063 ft) tall, about the same height as an 81-storey building . 
                          It was the first structure to reach a height of 300 metres . It is now taller than the 
                          Chrysler Building in New York City
 
        '413':
          description: Payload too large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '503':
          description: Server not ready
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

      requestBody:
        description: Form data contains either 'text' string field or 'text_file' text blob
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                text_file:
                  type: string
                  format: file
                text:
                  type: string
            example:
              text:
                The tower is 324 metres (1,063 ft) tall, about the same height as an 81-storey building, 
                and the tallest structure in Paris. Its base is square, measuring 125 metres (410 ft) on each side. 
                During its construction, the Eiffel Tower surpassed the Washington Monument to become the tallest 
                man-made structure in the world.

components:
  schemas:
    TextClassificationResult:
      type: object
      required:
        - emotion
        - summary
      properties:
          summary:
            type: object
            properties:
              emotion:
                type: array
                minItems: 6
                items:
                  $ref: '#/components/schemas/EmotionResult'
              summary_text:
                type: string
                maxLength: 2048
                
    EmotionResult:
      type: object
      required:
        - classifier_id
      properties:
        summary:
          type: object
            properties:
              summary_text:
                type: string
                maxLength: 2048
              emotion:
                type: array
                items:
                  type: object
                  properties:
                    label: string
                    score: number

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string