# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Galatea browser plugin build action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  plugin_build:

    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
        working-directory: client

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: yarn install
    - run: yarn build:extension

    - name: 'Build artifacts upload'
      uses: actions/upload-artifact@v2
      with:
        name: browser-plugin
        path: ${{ github.workspace }}/client/build
